<a href="https://colab.research.google.com/github/Patrick9876/BasicWebApp/blob/main/logistic_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Logistic Regression

## Importing the libraries

In [ ]:
import numpy as np
import pandas as pd

## Importing the dataset

In [1]:
dataset = pd.read_excel('jaggia_ba_1e_ch09_Data_Files.xlsx', sheet_name= 'Spam_Data')
X = dataset.iloc[:, 1:4].values
y = dataset.iloc[:, 0].values

dataset.head()


NameError: name 'pd' is not defined

Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [ ]:
print(X_train)

[[15  5 67]
 [14  6 98]
 [12  6 23]
 ...
 [13 11 28]
 [13 12 73]
 [12  9 90]]


In [ ]:
print(y_train)

[0 1 1 0 1 0 1 1 1 0 1 0 0 1 0 1 1 1 0 0 0 0 1 0 0 1 0 1 1 0 1 0 0 1 0 0 1
 1 1 0 1 1 1 1 0 0 0 1 1 0 1 1 0 0 0 0 1 0 0 1 1 0 0 0 1 0 0 0 1 0 0 1 1 1
 0 0 0 0 0 0 0 1 0 1 0 0 0 1 1 1 1 1 0 0 1 1 1 1 0 1 0 1 0 0 1 1 1 1 0 1 0
 1 1 1 0 1 0 0 0 0 1 1 0 0 0 1 0 1 1 0 1 1 1 0 0 0 0 0 1 0 0 1 0 1 1 1 1 0
 1 1 1 1 1 0 1 0 0 0 0 1 1 1 1 0 1 0 0 1 0 0 1 0 1 0 1 0 1 1 0 1 0 1 0 1 1
 1 1 1 1 1 0 1 0 1 0 1 1 1 0 0 1 1 1 0 0 0 1 1 1 1 0 1 0 0 1 1 0 0 1 1 1 0
 0 1 0 1 0 0 1 1 1 1 1 0 0 1 0 0 0 0 1 0 1 0 0 1 0 0 0 0 1 1 0 1 0 0 0 1 1
 0 1 1 1 1 1 1 1 0 0 1 0 1 1 0 1 1 0 1 0 1 0 1 0 0 1 0 1 0 1 0 1 0 1 0 0 1
 1 1 1 0 1 1 1 0 0 1 1 0 1 1 0 1 1 0 1 1 0 1 1 0 0 1 1 0 1 1 1 0 0 0 0 0 1
 0 0 0 1 0 1 1 0 0 0 1 0 0 1 0 1 1 1 1 1 0 1 1 0 0 1 1 0 1 1 1 1 1 1 0 1 0
 1 0 1 1 1]


In [ ]:
print(X_test)

[[ 13   2  20]
 [ 12   6  90]
 [ 12  10  83]
 [ 12   3 102]
 [ 12   1  63]
 [ 12  12  52]
 [ 24   9  62]
 [ 16   8  31]
 [ 13   7  62]
 [ 13   7  94]
 [ 16   9  97]
 [ 13   3  35]
 [ 17   8  34]
 [ 13   4  19]
 [ 12  11  29]
 [ 12   9  54]
 [ 14   8  47]
 [ 12   9  45]
 [ 13   0  69]
 [ 12  12  28]
 [ 13   4  78]
 [ 12   3  82]
 [ 16  12  52]
 [ 18   7  24]
 [ 15   9  63]
 [ 15   6  59]
 [ 13   2  81]
 [ 12   4  73]
 [ 17   1  87]
 [ 13   0 102]
 [ 12   8  45]
 [ 14   7  24]
 [ 12  11  57]
 [ 16  11  48]
 [ 19  11  83]
 [ 13   1  24]
 [ 13  12  26]
 [ 13   7  49]
 [ 12  11  84]
 [ 12   7  80]
 [ 12   6  70]
 [ 17   5  50]
 [ 12  11  89]
 [ 13   4  64]
 [ 12   3  24]
 [ 15   1  58]
 [ 36   5  23]
 [ 13  10  71]
 [ 13   4  44]
 [ 25   2  53]
 [ 14  10  82]
 [ 13   3  73]
 [ 15   3  78]
 [ 12   6 102]
 [ 13   2  77]
 [ 13  11  27]
 [ 12   4  58]
 [ 13   5 100]
 [ 14   6  20]
 [ 17   1  67]
 [ 12   5 102]
 [ 13   6  76]
 [ 17  10  70]
 [ 15  11  87]
 [ 18   3  70]
 [ 14   3  28]
 [ 13  10 

In [ ]:
print(y_test)

[0 0 1 1 0 1 1 1 0 1 1 0 1 1 1 0 0 0 0 1 0 0 1 1 1 0 0 0 0 0 0 1 1 1 1 0 1
 1 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 1 0 1 0 1 1 0 1 0 0 1 1 1 1 0 0 1 0 0 0 1
 0 0 1 0 0 0 1 0 0 1 0 1 1 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 1 1 1 0 1 1 1 1
 0 1 0 0 1 0 0 0 1 1 0 0 1 1]


## Training the Logistic Regression model on the Training set

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

## Predicting the Test set results

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [1 0]
 [1 1]
 [0 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [1 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [0 1]]


## Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[52 15]
 [14 44]]


0.768